export const CREATE_JOB_INIT = "CREATE_JOB_INIT";
export const CREATE_JOB_SUCC = "CREATE_JOB_SUCC";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";

export const FETCH_EMPLOYER_JOBS_INIT = "FETCH_EMPLOYER_JOBS_INIT";
export const FETCH_EMPLOYER_JOBS_SUCC = "FETCH_EMPLOYER_JOBS_SUCC";
export const FETCH_EMPLOYER_JOBS_FAIL = "FETCH_EMPLOYER_JOBS_FAIL";

export const FETCH_ALL_JOBS_INIT = "FETCH_ALL_JOBS_INIT";
export const FETCH_ALL_JOBS_SUCC = "FETCH_ALL_JOBS_SUCC";
export const FETCH_ALL_JOBS_FAIL = "FETCH_ALL_JOBS_FAIL";

export const FETCH_SINGLE_JOB_INIT = "FETCH_SINGLE_JOB_INIT";
export const FETCH_SINGLE_JOB_SUCC = "FETCH_SINGLE_JOB_SUCC";
export const FETCH_SINGLE_JOB_FAIL = "FETCH_SINGLE_JOB_FAIL";
