export const USER_LOGIN_INIT = "USER_LOGIN_INIT";
export const USER_LOGIN_SUCC = "USER_LOGIN_SUCC";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_CREATE_INIT = "USER_CREATE_INIT";
export const USER_CREATE_SUCC = "USER_CREATE_SUCC";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const PROFILE_CREATE_INIT = "PROFILE_CREATE_INIT";
export const PROFILE_CREATE_SUCC = "PROFILE_CREATE_SUCC";
export const PROFILE_CREATE_FAIL = "PROFILE_CREATE_FAIL";

export const PROFILE_FETCH_INIT = "PROFILE_FETCH_INIT";
export const PROFILE_FETCH_SUCC = "PROFILE_FETCH_SUCC";
export const PROFILE_FETCH_FAIL = "PROFILE_FETCH_FAIL";

export const EXPERIENCE_CREATE_INIT = "EXPERIENCE_CREATE_INIT";
export const EXPERIENCE_CREATE_SUCC = "EXPERIENCE_CREATE_SUCC";
export const EXPERIENCE_CREATE_FAIL = "EXPERIENCE_CREATE_FAIL";

export const EXPERIENCE_REMOVE_INIT = "EXPERIENCE_REMOVE_INI";
export const EXPERIENCE_REMOVE_SUCC = "EXPERIENCE_REMOVE_SUCC";
export const EXPERIENCE_REMOVE_FAIL = "EXPERIENCE_REMOVE_FAIL";

export const EDUCATION_CREATE_INIT = "EDUCATION_CREATE_INIT";
export const EDUCATION_CREATE_SUCC = "EDUCATION_CREATE_SUCC";
export const EDUCATION_CREATE_FAIL = "EDUCATION_CREATE_FAIL";
